"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.pagination import Pagination
from workspaces_cli.model.tag import Tag
globals()['Pagination'] = Pagination
globals()['Tag'] = Tag
from workspaces_cli.model.inline_response2003 import InlineResponse2003


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
