"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.tag import Tag


class TestTag(unittest.TestCase):
    """Tag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTag(self):
        """Test Tag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
