"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import workspaces_cli
from workspaces_cli.api.rest_api import RestApi  # noqa: E501


class TestRestApi(unittest.TestCase):
    """RestApi unit test stubs"""

    def setUp(self):
        self.api = RestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delimage(self):
        """Test case for delimage

        Delete a Workspace Image from the workspace.  # noqa: E501
        """
        pass

    def test_get_description(self):
        """Test case for get_description

        Used to retrieve description for a repository.  # noqa: E501
        """
        pass

    def test_get_info(self):
        """Test case for get_info

        Used to retrieve a list of contexts of a repository.  # noqa: E501
        """
        pass

    def test_osbrepository_get(self):
        """Test case for osbrepository_get

        Used to list all available repositories.  # noqa: E501
        """
        pass

    def test_osbrepository_id_delete(self):
        """Test case for osbrepository_id_delete

        Delete a OSBRepository.  # noqa: E501
        """
        pass

    def test_osbrepository_id_get(self):
        """Test case for osbrepository_id_get

        Used to retrieve a repository.  # noqa: E501
        """
        pass

    def test_osbrepository_id_put(self):
        """Test case for osbrepository_id_put

        Update a OSB repository.  # noqa: E501
        """
        pass

    def test_osbrepository_post(self):
        """Test case for osbrepository_post

        Used to save a OSB Repository. The user_id (keycloak user id) will be automatically filled with the current user  # noqa: E501
        """
        pass

    def test_tag_get(self):
        """Test case for tag_get

        Used to list all available tags.  # noqa: E501
        """
        pass

    def test_tag_id_delete(self):
        """Test case for tag_id_delete

        Delete an tag from the repository.  # noqa: E501
        """
        pass

    def test_tag_id_get(self):
        """Test case for tag_id_get

        Used to retrieve an tag from the repository.  # noqa: E501
        """
        pass

    def test_tag_id_put(self):
        """Test case for tag_id_put

        Update an tag in the repository.  # noqa: E501
        """
        pass

    def test_tag_post(self):
        """Test case for tag_post

        Used to save a Tag to the repository. The user_id (keycloak user id) will be automatically filled with the current user  # noqa: E501
        """
        pass

    def test_volumestorage_get(self):
        """Test case for volumestorage_get

        Used to list all available volumestorages.  # noqa: E501
        """
        pass

    def test_volumestorage_id_delete(self):
        """Test case for volumestorage_id_delete

        Delete an volumestorage from the repository.  # noqa: E501
        """
        pass

    def test_volumestorage_id_get(self):
        """Test case for volumestorage_id_get

        Used to retrieve an volumestorage from the repository.  # noqa: E501
        """
        pass

    def test_volumestorage_id_put(self):
        """Test case for volumestorage_id_put

        Update an volumestorage in the repository.  # noqa: E501
        """
        pass

    def test_volumestorage_post(self):
        """Test case for volumestorage_post

        Used to save a VolumeStorage to the repository. The user_id (keycloak user id) will be automatically filled with the current user  # noqa: E501
        """
        pass

    def test_workspace_get(self):
        """Test case for workspace_get

        Used to list all available workspaces.  # noqa: E501
        """
        pass

    def test_workspace_id_delete(self):
        """Test case for workspace_id_delete

        Delete a workspace from the repository.  # noqa: E501
        """
        pass

    def test_workspace_id_get(self):
        """Test case for workspace_id_get

        Used to retrieve a workspace from the repository.  # noqa: E501
        """
        pass

    def test_workspace_id_put(self):
        """Test case for workspace_id_put

        Update a workspace in the repository.  # noqa: E501
        """
        pass

    def test_workspace_post(self):
        """Test case for workspace_post

        Used to save a Workspace to the repository. The user_id (keycloak user id) will be automatically filled with the current user  # noqa: E501
        """
        pass

    def test_workspaceresource_id_delete(self):
        """Test case for workspaceresource_id_delete

        Delete a WorkspaceResource.  # noqa: E501
        """
        pass

    def test_workspaceresource_id_get(self):
        """Test case for workspaceresource_id_get

        Used to retrieve a WorkspaceResource.  # noqa: E501
        """
        pass

    def test_workspaceresource_id_put(self):
        """Test case for workspaceresource_id_put

        Update the WorkspaceResource.  # noqa: E501
        """
        pass

    def test_workspaceresource_post(self):
        """Test case for workspaceresource_post

        Used to save a WorkspaceResource to the repository.  # noqa: E501
        """
        pass

    def test_workspaces_controllers_workspace_controller_addimage(self):
        """Test case for workspaces_controllers_workspace_controller_addimage

        Adds and image to the workspace.  # noqa: E501
        """
        pass

    def test_workspaces_controllers_workspace_controller_import_resources(self):
        """Test case for workspaces_controllers_workspace_controller_import_resources

        Imports the ResourceOrigins into the Workspace and creates/updates the workspace resources  # noqa: E501
        """
        pass

    def test_workspaces_controllers_workspace_controller_setthumbnail(self):
        """Test case for workspaces_controllers_workspace_controller_setthumbnail

        Sets the thumbnail of the workspace.  # noqa: E501
        """
        pass

    def test_workspaces_controllers_workspace_controller_workspace_clone(self):
        """Test case for workspaces_controllers_workspace_controller_workspace_clone

        Clones a workspace  # noqa: E501
        """
        pass

    def test_workspaces_controllers_workspace_resource_controller_open(self):
        """Test case for workspaces_controllers_workspace_resource_controller_open

        Used to register a WorkspaceResource open action. The WorkspaceResource timestamp last open will be updated  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
