"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.pagination import Pagination
from workspaces_cli.model.volume_storage import VolumeStorage
globals()['Pagination'] = Pagination
globals()['VolumeStorage'] = VolumeStorage
from workspaces_cli.model.inline_response2002 import InlineResponse2002


class TestInlineResponse2002(unittest.TestCase):
    """InlineResponse2002 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002(self):
        """Test InlineResponse2002"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2002()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
