"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.resource_status import ResourceStatus
from workspaces_cli.model.resource_type import ResourceType
from workspaces_cli.model.workspace_resource_base import WorkspaceResourceBase
from workspaces_cli.model.workspace_resource_entity_all_of import WorkspaceResourceEntityAllOf
globals()['ResourceStatus'] = ResourceStatus
globals()['ResourceType'] = ResourceType
globals()['WorkspaceResourceBase'] = WorkspaceResourceBase
globals()['WorkspaceResourceEntityAllOf'] = WorkspaceResourceEntityAllOf
from workspaces_cli.model.workspace_resource_entity import WorkspaceResourceEntity


class TestWorkspaceResourceEntity(unittest.TestCase):
    """WorkspaceResourceEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceResourceEntity(self):
        """Test WorkspaceResourceEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceResourceEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
