"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.dandi_repository_resource import DandiRepositoryResource
from workspaces_cli.model.figshare_repository_resource import FigshareRepositoryResource
from workspaces_cli.model.git_repository_resource import GITRepositoryResource
globals()['DandiRepositoryResource'] = DandiRepositoryResource
globals()['FigshareRepositoryResource'] = FigshareRepositoryResource
globals()['GITRepositoryResource'] = GITRepositoryResource
from workspaces_cli.model.repository_resource import RepositoryResource


class TestRepositoryResource(unittest.TestCase):
    """RepositoryResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryResource(self):
        """Test RepositoryResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
