"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.repository_type import RepositoryType


class TestRepositoryType(unittest.TestCase):
    """RepositoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryType(self):
        """Test RepositoryType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
