"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.workspace_resource_entity import WorkspaceResourceEntity
globals()['WorkspaceResourceEntity'] = WorkspaceResourceEntity
from workspaces_cli.model.workspace_entity_all_of import WorkspaceEntityAllOf


class TestWorkspaceEntityAllOf(unittest.TestCase):
    """WorkspaceEntityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceEntityAllOf(self):
        """Test WorkspaceEntityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceEntityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
