"""
    Workspaces manager API

    Opensource Brain Platform - Reference Workspaces manager API  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import workspaces_cli
from workspaces_cli.model.repository_type import RepositoryType
globals()['RepositoryType'] = RepositoryType
from workspaces_cli.model.osb_repository_base import OSBRepositoryBase


class TestOSBRepositoryBase(unittest.TestCase):
    """OSBRepositoryBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOSBRepositoryBase(self):
        """Test OSBRepositoryBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OSBRepositoryBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
