from workspaces.service.osbrepository.adapters.dandiadapter import DandiAdapter
from workspaces.service.osbrepository.adapters.figshareadapter import FigShareAdapter
from workspaces.service.osbrepository.adapters.githubadapter import GitHubAdapter
