harness:
  name: workspaces
  subdomain: workspaces
  service:
     port: 8080
     auto: true
     name: workspaces
  secured: false
  sentry: true
  deployment:
    auto: true
    port: 8080
    volume:
      name: workspaces-images
      size: 4G
      mountpath: /usr/src/app/workspaces/static/workspaces
postgres:
  name: workspaces-postgres-host
  port: 5432
  image: postgres:latest
  initialdb: workspaces
  user: workspace
  password: secret
  datavolume: /opt/data/
  pgdata: /opt/data/pgdata
