harness:
  sentry: false
  database:
    size: 10Gi
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
  deployment:
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 750Mi

    