from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from accounts_api.models.base_model import Model
from accounts_api import util


class GetUsers200ResponsePagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, current_page=None, per_page=None, number_of_pages=None):  # noqa: E501
        """GetUsers200ResponsePagination - a model defined in OpenAPI

        :param total: The total of this GetUsers200ResponsePagination.  # noqa: E501
        :type total: int
        :param current_page: The current_page of this GetUsers200ResponsePagination.  # noqa: E501
        :type current_page: int
        :param per_page: The per_page of this GetUsers200ResponsePagination.  # noqa: E501
        :type per_page: int
        :param number_of_pages: The number_of_pages of this GetUsers200ResponsePagination.  # noqa: E501
        :type number_of_pages: int
        """
        self.openapi_types = {
            'total': int,
            'current_page': int,
            'per_page': int,
            'number_of_pages': int
        }

        self.attribute_map = {
            'total': 'total',
            'current_page': 'current_page',
            'per_page': 'per_page',
            'number_of_pages': 'number_of_pages'
        }

        self._total = total
        self._current_page = current_page
        self._per_page = per_page
        self._number_of_pages = number_of_pages

    @classmethod
    def from_dict(cls, dikt) -> 'GetUsers200ResponsePagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_users_200_response_pagination of this GetUsers200ResponsePagination.  # noqa: E501
        :rtype: GetUsers200ResponsePagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this GetUsers200ResponsePagination.


        :return: The total of this GetUsers200ResponsePagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this GetUsers200ResponsePagination.


        :param total: The total of this GetUsers200ResponsePagination.
        :type total: int
        """

        self._total = total

    @property
    def current_page(self) -> int:
        """Gets the current_page of this GetUsers200ResponsePagination.


        :return: The current_page of this GetUsers200ResponsePagination.
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page: int):
        """Sets the current_page of this GetUsers200ResponsePagination.


        :param current_page: The current_page of this GetUsers200ResponsePagination.
        :type current_page: int
        """

        self._current_page = current_page

    @property
    def per_page(self) -> int:
        """Gets the per_page of this GetUsers200ResponsePagination.


        :return: The per_page of this GetUsers200ResponsePagination.
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page: int):
        """Sets the per_page of this GetUsers200ResponsePagination.


        :param per_page: The per_page of this GetUsers200ResponsePagination.
        :type per_page: int
        """

        self._per_page = per_page

    @property
    def number_of_pages(self) -> int:
        """Gets the number_of_pages of this GetUsers200ResponsePagination.


        :return: The number_of_pages of this GetUsers200ResponsePagination.
        :rtype: int
        """
        return self._number_of_pages

    @number_of_pages.setter
    def number_of_pages(self, number_of_pages: int):
        """Sets the number_of_pages of this GetUsers200ResponsePagination.


        :param number_of_pages: The number_of_pages of this GetUsers200ResponsePagination.
        :type number_of_pages: int
        """

        self._number_of_pages = number_of_pages
