from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from accounts_api.models.base_model import Model
from accounts_api.models.get_users200_response_pagination import GetUsers200ResponsePagination
from accounts_api.models.user import User
from accounts_api import util

from accounts_api.models.get_users200_response_pagination import GetUsers200ResponsePagination  # noqa: E501
from accounts_api.models.user import User  # noqa: E501

class GetUsers200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, users=None, pagination=None):  # noqa: E501
        """GetUsers200Response - a model defined in OpenAPI

        :param users: The users of this GetUsers200Response.  # noqa: E501
        :type users: List[User]
        :param pagination: The pagination of this GetUsers200Response.  # noqa: E501
        :type pagination: GetUsers200ResponsePagination
        """
        self.openapi_types = {
            'users': List[User],
            'pagination': GetUsers200ResponsePagination
        }

        self.attribute_map = {
            'users': 'users',
            'pagination': 'pagination'
        }

        self._users = users
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'GetUsers200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_users_200_response of this GetUsers200Response.  # noqa: E501
        :rtype: GetUsers200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[User]:
        """Gets the users of this GetUsers200Response.


        :return: The users of this GetUsers200Response.
        :rtype: List[User]
        """
        return self._users

    @users.setter
    def users(self, users: List[User]):
        """Sets the users of this GetUsers200Response.


        :param users: The users of this GetUsers200Response.
        :type users: List[User]
        """

        self._users = users

    @property
    def pagination(self) -> GetUsers200ResponsePagination:
        """Gets the pagination of this GetUsers200Response.


        :return: The pagination of this GetUsers200Response.
        :rtype: GetUsers200ResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: GetUsers200ResponsePagination):
        """Sets the pagination of this GetUsers200Response.


        :param pagination: The pagination of this GetUsers200Response.
        :type pagination: GetUsers200ResponsePagination
        """

        self._pagination = pagination
