env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
  - ./.babelrc.js
plugins:
  - react
ignorePatterns:
  - node_modules/
  - dist/
  - /src/apiclient/
  - webpack*.js
rules:
  no-console: 0
  func-style: 0
  consistent-return: 0
  no-unused-vars: 0
  no-func-assign: 1
  no-cond-assign: 1
  no-empty: 1
  no-undef: 1
  react/display-name: 1
  no-case-declarations: 1
  no-inner-declarations: 1
  prefer-arrow-callback:
    - 2
    - allowNamedFunctions: false
      allowUnboundThis: false
  react/prop-types: 0
  react/forbid-prop-types: 0
  react/no-unused-prop-types: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  curly: 2
  no-tabs: 2
  arrow-spacing: 2
  no-unneeded-ternary: 2
  object-curly-spacing:
    - 2
    - always
  indent:
    - 2
    - 2
    - SwitchCase: 1
