/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * GIT hub specific attributes of the RepositoryResource
 * @export
 * @interface RepositoryResourceBaseAllOf
 */
export interface RepositoryResourceBaseAllOf {
    /**
     * OSB Repository id
     * @type {number}
     * @memberof RepositoryResourceBaseAllOf
     */
    osbrepositoryId?: number;
    /**
     * File size in bytes of the RepositoryResource
     * @type {number}
     * @memberof RepositoryResourceBaseAllOf
     */
    size?: number;
    /**
     * Date/time the ReposityResource is last modified
     * @type {Date}
     * @memberof RepositoryResourceBaseAllOf
     */
    timestampModified?: Date;
}

export function RepositoryResourceBaseAllOfFromJSON(json: any): RepositoryResourceBaseAllOf {
    return RepositoryResourceBaseAllOfFromJSONTyped(json, false);
}

export function RepositoryResourceBaseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryResourceBaseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'osbrepositoryId': !exists(json, 'osbrepository_id') ? undefined : json['osbrepository_id'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'timestampModified': !exists(json, 'timestamp_modified') ? undefined : (new Date(json['timestamp_modified'])),
    };
}

export function RepositoryResourceBaseAllOfToJSON(value?: RepositoryResourceBaseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'osbrepository_id': value.osbrepositoryId,
        'size': value.size,
        'timestamp_modified': value.timestampModified === undefined ? undefined : (value.timestampModified.toISOString()),
    };
}


