# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.ember_upload_part import EmberUploadPart
from workspaces import util

from workspaces.models.ember_upload_part import EmberUploadPart  # noqa: E501

class EmberUploadUrlsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dandiset_id=None, upload_id=None, path=None, parts=None, blob_id=None):  # noqa: E501
        """EmberUploadUrlsResponse - a model defined in OpenAPI

        :param dandiset_id: The dandiset_id of this EmberUploadUrlsResponse.  # noqa: E501
        :type dandiset_id: str
        :param upload_id: The upload_id of this EmberUploadUrlsResponse.  # noqa: E501
        :type upload_id: str
        :param path: The path of this EmberUploadUrlsResponse.  # noqa: E501
        :type path: str
        :param parts: The parts of this EmberUploadUrlsResponse.  # noqa: E501
        :type parts: List[EmberUploadPart]
        :param blob_id: The blob_id of this EmberUploadUrlsResponse.  # noqa: E501
        :type blob_id: str
        """
        self.openapi_types = {
            'dandiset_id': str,
            'upload_id': str,
            'path': str,
            'parts': List[EmberUploadPart],
            'blob_id': str
        }

        self.attribute_map = {
            'dandiset_id': 'dandiset_id',
            'upload_id': 'upload_id',
            'path': 'path',
            'parts': 'parts',
            'blob_id': 'blob_id'
        }

        self._dandiset_id = dandiset_id
        self._upload_id = upload_id
        self._path = path
        self._parts = parts
        self._blob_id = blob_id

    @classmethod
    def from_dict(cls, dikt) -> 'EmberUploadUrlsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmberUploadUrlsResponse of this EmberUploadUrlsResponse.  # noqa: E501
        :rtype: EmberUploadUrlsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dandiset_id(self):
        """Gets the dandiset_id of this EmberUploadUrlsResponse.


        :return: The dandiset_id of this EmberUploadUrlsResponse.
        :rtype: str
        """
        return self._dandiset_id

    @dandiset_id.setter
    def dandiset_id(self, dandiset_id):
        """Sets the dandiset_id of this EmberUploadUrlsResponse.


        :param dandiset_id: The dandiset_id of this EmberUploadUrlsResponse.
        :type dandiset_id: str
        """
        if dandiset_id is None:
            raise ValueError("Invalid value for `dandiset_id`, must not be `None`")  # noqa: E501

        self._dandiset_id = dandiset_id

    @property
    def upload_id(self):
        """Gets the upload_id of this EmberUploadUrlsResponse.

        Absent when the content was already in EMBER-DANDI.  # noqa: E501

        :return: The upload_id of this EmberUploadUrlsResponse.
        :rtype: str
        """
        return self._upload_id

    @upload_id.setter
    def upload_id(self, upload_id):
        """Sets the upload_id of this EmberUploadUrlsResponse.

        Absent when the content was already in EMBER-DANDI.  # noqa: E501

        :param upload_id: The upload_id of this EmberUploadUrlsResponse.
        :type upload_id: str
        """

        self._upload_id = upload_id

    @property
    def path(self):
        """Gets the path of this EmberUploadUrlsResponse.

        Asset path, derived server-side from the caller's identity.  # noqa: E501

        :return: The path of this EmberUploadUrlsResponse.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this EmberUploadUrlsResponse.

        Asset path, derived server-side from the caller's identity.  # noqa: E501

        :param path: The path of this EmberUploadUrlsResponse.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def parts(self):
        """Gets the parts of this EmberUploadUrlsResponse.


        :return: The parts of this EmberUploadUrlsResponse.
        :rtype: List[EmberUploadPart]
        """
        return self._parts

    @parts.setter
    def parts(self, parts):
        """Sets the parts of this EmberUploadUrlsResponse.


        :param parts: The parts of this EmberUploadUrlsResponse.
        :type parts: List[EmberUploadPart]
        """
        if parts is None:
            raise ValueError("Invalid value for `parts`, must not be `None`")  # noqa: E501

        self._parts = parts

    @property
    def blob_id(self):
        """Gets the blob_id of this EmberUploadUrlsResponse.

        Set only when the content was already in EMBER-DANDI (parts is then empty).  # noqa: E501

        :return: The blob_id of this EmberUploadUrlsResponse.
        :rtype: str
        """
        return self._blob_id

    @blob_id.setter
    def blob_id(self, blob_id):
        """Sets the blob_id of this EmberUploadUrlsResponse.

        Set only when the content was already in EMBER-DANDI (parts is then empty).  # noqa: E501

        :param blob_id: The blob_id of this EmberUploadUrlsResponse.
        :type blob_id: str
        """

        self._blob_id = blob_id
