# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces import util

class EmberUploadUrlsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, dandiset_id=None, filename=None, size=None, dandi_etag=None):  # noqa: E501
        """EmberUploadUrlsRequest - a model defined in OpenAPI

        :param username: The username of this EmberUploadUrlsRequest.  # noqa: E501
        :type username: str
        :param dandiset_id: The dandiset_id of this EmberUploadUrlsRequest.  # noqa: E501
        :type dandiset_id: str
        :param filename: The filename of this EmberUploadUrlsRequest.  # noqa: E501
        :type filename: str
        :param size: The size of this EmberUploadUrlsRequest.  # noqa: E501
        :type size: int
        :param dandi_etag: The dandi_etag of this EmberUploadUrlsRequest.  # noqa: E501
        :type dandi_etag: str
        """
        self.openapi_types = {
            'username': str,
            'dandiset_id': str,
            'filename': str,
            'size': int,
            'dandi_etag': str
        }

        self.attribute_map = {
            'username': 'username',
            'dandiset_id': 'dandiset_id',
            'filename': 'filename',
            'size': 'size',
            'dandi_etag': 'dandi_etag'
        }

        self._username = username
        self._dandiset_id = dandiset_id
        self._filename = filename
        self._size = size
        self._dandi_etag = dandi_etag

    @classmethod
    def from_dict(cls, dikt) -> 'EmberUploadUrlsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmberUploadUrlsRequest of this EmberUploadUrlsRequest.  # noqa: E501
        :rtype: EmberUploadUrlsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this EmberUploadUrlsRequest.

        Keycloak username whose EMBER-DANDI key (user attribute EMBER_API_KEY) signs the upload.  # noqa: E501

        :return: The username of this EmberUploadUrlsRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this EmberUploadUrlsRequest.

        Keycloak username whose EMBER-DANDI key (user attribute EMBER_API_KEY) signs the upload.  # noqa: E501

        :param username: The username of this EmberUploadUrlsRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def dandiset_id(self):
        """Gets the dandiset_id of this EmberUploadUrlsRequest.

        The EMBER-DANDI dandiset to upload into, chosen by the client.  # noqa: E501

        :return: The dandiset_id of this EmberUploadUrlsRequest.
        :rtype: str
        """
        return self._dandiset_id

    @dandiset_id.setter
    def dandiset_id(self, dandiset_id):
        """Sets the dandiset_id of this EmberUploadUrlsRequest.

        The EMBER-DANDI dandiset to upload into, chosen by the client.  # noqa: E501

        :param dandiset_id: The dandiset_id of this EmberUploadUrlsRequest.
        :type dandiset_id: str
        """
        if dandiset_id is None:
            raise ValueError("Invalid value for `dandiset_id`, must not be `None`")  # noqa: E501

        self._dandiset_id = dandiset_id

    @property
    def filename(self):
        """Gets the filename of this EmberUploadUrlsRequest.


        :return: The filename of this EmberUploadUrlsRequest.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this EmberUploadUrlsRequest.


        :param filename: The filename of this EmberUploadUrlsRequest.
        :type filename: str
        """
        if filename is None:
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def size(self):
        """Gets the size of this EmberUploadUrlsRequest.


        :return: The size of this EmberUploadUrlsRequest.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this EmberUploadUrlsRequest.


        :param size: The size of this EmberUploadUrlsRequest.
        :type size: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def dandi_etag(self):
        """Gets the dandi_etag of this EmberUploadUrlsRequest.

        S3-multipart digest in DANDI's format (32 hex chars, a dash, the part count), computed in the browser since the bytes never reach this server.  # noqa: E501

        :return: The dandi_etag of this EmberUploadUrlsRequest.
        :rtype: str
        """
        return self._dandi_etag

    @dandi_etag.setter
    def dandi_etag(self, dandi_etag):
        """Sets the dandi_etag of this EmberUploadUrlsRequest.

        S3-multipart digest in DANDI's format (32 hex chars, a dash, the part count), computed in the browser since the bytes never reach this server.  # noqa: E501

        :param dandi_etag: The dandi_etag of this EmberUploadUrlsRequest.
        :type dandi_etag: str
        """
        if dandi_etag is None:
            raise ValueError("Invalid value for `dandi_etag`, must not be `None`")  # noqa: E501

        self._dandi_etag = dandi_etag
