# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces import util

class EmberValidateUploadResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, asset_id=None, asset_path=None, dandiset_id=None, dandiset_url=None, download_url=None):  # noqa: E501
        """EmberValidateUploadResponse - a model defined in OpenAPI

        :param asset_id: The asset_id of this EmberValidateUploadResponse.  # noqa: E501
        :type asset_id: str
        :param asset_path: The asset_path of this EmberValidateUploadResponse.  # noqa: E501
        :type asset_path: str
        :param dandiset_id: The dandiset_id of this EmberValidateUploadResponse.  # noqa: E501
        :type dandiset_id: str
        :param dandiset_url: The dandiset_url of this EmberValidateUploadResponse.  # noqa: E501
        :type dandiset_url: str
        :param download_url: The download_url of this EmberValidateUploadResponse.  # noqa: E501
        :type download_url: str
        """
        self.openapi_types = {
            'asset_id': str,
            'asset_path': str,
            'dandiset_id': str,
            'dandiset_url': str,
            'download_url': str
        }

        self.attribute_map = {
            'asset_id': 'asset_id',
            'asset_path': 'asset_path',
            'dandiset_id': 'dandiset_id',
            'dandiset_url': 'dandiset_url',
            'download_url': 'download_url'
        }

        self._asset_id = asset_id
        self._asset_path = asset_path
        self._dandiset_id = dandiset_id
        self._dandiset_url = dandiset_url
        self._download_url = download_url

    @classmethod
    def from_dict(cls, dikt) -> 'EmberValidateUploadResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmberValidateUploadResponse of this EmberValidateUploadResponse.  # noqa: E501
        :rtype: EmberValidateUploadResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def asset_id(self):
        """Gets the asset_id of this EmberValidateUploadResponse.


        :return: The asset_id of this EmberValidateUploadResponse.
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this EmberValidateUploadResponse.


        :param asset_id: The asset_id of this EmberValidateUploadResponse.
        :type asset_id: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def asset_path(self):
        """Gets the asset_path of this EmberValidateUploadResponse.


        :return: The asset_path of this EmberValidateUploadResponse.
        :rtype: str
        """
        return self._asset_path

    @asset_path.setter
    def asset_path(self, asset_path):
        """Sets the asset_path of this EmberValidateUploadResponse.


        :param asset_path: The asset_path of this EmberValidateUploadResponse.
        :type asset_path: str
        """
        if asset_path is None:
            raise ValueError("Invalid value for `asset_path`, must not be `None`")  # noqa: E501

        self._asset_path = asset_path

    @property
    def dandiset_id(self):
        """Gets the dandiset_id of this EmberValidateUploadResponse.


        :return: The dandiset_id of this EmberValidateUploadResponse.
        :rtype: str
        """
        return self._dandiset_id

    @dandiset_id.setter
    def dandiset_id(self, dandiset_id):
        """Sets the dandiset_id of this EmberValidateUploadResponse.


        :param dandiset_id: The dandiset_id of this EmberValidateUploadResponse.
        :type dandiset_id: str
        """

        self._dandiset_id = dandiset_id

    @property
    def dandiset_url(self):
        """Gets the dandiset_url of this EmberValidateUploadResponse.


        :return: The dandiset_url of this EmberValidateUploadResponse.
        :rtype: str
        """
        return self._dandiset_url

    @dandiset_url.setter
    def dandiset_url(self, dandiset_url):
        """Sets the dandiset_url of this EmberValidateUploadResponse.


        :param dandiset_url: The dandiset_url of this EmberValidateUploadResponse.
        :type dandiset_url: str
        """

        self._dandiset_url = dandiset_url

    @property
    def download_url(self):
        """Gets the download_url of this EmberValidateUploadResponse.

        Where the asset's bytes can be fetched from, e.g. by OSB's workspace import.  # noqa: E501

        :return: The download_url of this EmberValidateUploadResponse.
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this EmberValidateUploadResponse.

        Where the asset's bytes can be fetched from, e.g. by OSB's workspace import.  # noqa: E501

        :param download_url: The download_url of this EmberValidateUploadResponse.
        :type download_url: str
        """
        if download_url is None:
            raise ValueError("Invalid value for `download_url`, must not be `None`")  # noqa: E501

        self._download_url = download_url
