# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.figshare_repository import FigshareRepository
from workspaces.models.pagination import Pagination
from workspaces import util

from workspaces.models.figshare_repository import FigshareRepository  # noqa: E501
from workspaces.models.pagination import Pagination  # noqa: E501

class InlineResponse2003(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pagination=None, figsharerepositories=None):  # noqa: E501
        """InlineResponse2003 - a model defined in OpenAPI

        :param pagination: The pagination of this InlineResponse2003.  # noqa: E501
        :type pagination: Pagination
        :param figsharerepositories: The figsharerepositories of this InlineResponse2003.  # noqa: E501
        :type figsharerepositories: List[FigshareRepository]
        """
        self.openapi_types = {
            'pagination': Pagination,
            'figsharerepositories': List[FigshareRepository]
        }

        self.attribute_map = {
            'pagination': 'pagination',
            'figsharerepositories': 'figsharerepositories'
        }

        self._pagination = pagination
        self._figsharerepositories = figsharerepositories

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse2003.


        :return: The pagination of this InlineResponse2003.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse2003.


        :param pagination: The pagination of this InlineResponse2003.
        :type pagination: Pagination
        """

        self._pagination = pagination

    @property
    def figsharerepositories(self):
        """Gets the figsharerepositories of this InlineResponse2003.


        :return: The figsharerepositories of this InlineResponse2003.
        :rtype: List[FigshareRepository]
        """
        return self._figsharerepositories

    @figsharerepositories.setter
    def figsharerepositories(self, figsharerepositories):
        """Sets the figsharerepositories of this InlineResponse2003.


        :param figsharerepositories: The figsharerepositories of this InlineResponse2003.
        :type figsharerepositories: List[FigshareRepository]
        """

        self._figsharerepositories = figsharerepositories
