# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.osb_repository import OSBRepository
from workspaces.models.pagination import Pagination
from workspaces import util

from workspaces.models.osb_repository import OSBRepository  # noqa: E501
from workspaces.models.pagination import Pagination  # noqa: E501

class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pagination=None, gitrepositories=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param pagination: The pagination of this InlineResponse2001.  # noqa: E501
        :type pagination: Pagination
        :param gitrepositories: The gitrepositories of this InlineResponse2001.  # noqa: E501
        :type gitrepositories: List[OSBRepository]
        """
        self.openapi_types = {
            'pagination': Pagination,
            'gitrepositories': List[OSBRepository]
        }

        self.attribute_map = {
            'pagination': 'pagination',
            'gitrepositories': 'gitrepositories'
        }

        self._pagination = pagination
        self._gitrepositories = gitrepositories

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse2001.


        :return: The pagination of this InlineResponse2001.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse2001.


        :param pagination: The pagination of this InlineResponse2001.
        :type pagination: Pagination
        """

        self._pagination = pagination

    @property
    def gitrepositories(self):
        """Gets the gitrepositories of this InlineResponse2001.


        :return: The gitrepositories of this InlineResponse2001.
        :rtype: List[OSBRepository]
        """
        return self._gitrepositories

    @gitrepositories.setter
    def gitrepositories(self, gitrepositories):
        """Sets the gitrepositories of this InlineResponse2001.


        :param gitrepositories: The gitrepositories of this InlineResponse2001.
        :type gitrepositories: List[OSBRepository]
        """

        self._gitrepositories = gitrepositories
