# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.repository_type import RepositoryType
from workspaces.models.workspace_resource import WorkspaceResource
from workspaces import util

from workspaces.models.repository_type import RepositoryType  # noqa: E501
from workspaces.models.workspace_resource import WorkspaceResource  # noqa: E501

class OSBRepository(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, repository_type=None, repository_content_types=None, auto_sync=True, uri=None, user_id=None, default_context=None, resources=None):  # noqa: E501
        """OSBRepository - a model defined in OpenAPI

        :param id: The id of this OSBRepository.  # noqa: E501
        :type id: int
        :param name: The name of this OSBRepository.  # noqa: E501
        :type name: str
        :param repository_type: The repository_type of this OSBRepository.  # noqa: E501
        :type repository_type: RepositoryType
        :param repository_content_types: The repository_content_types of this OSBRepository.  # noqa: E501
        :type repository_content_types: str
        :param auto_sync: The auto_sync of this OSBRepository.  # noqa: E501
        :type auto_sync: bool
        :param uri: The uri of this OSBRepository.  # noqa: E501
        :type uri: str
        :param user_id: The user_id of this OSBRepository.  # noqa: E501
        :type user_id: str
        :param default_context: The default_context of this OSBRepository.  # noqa: E501
        :type default_context: str
        :param resources: The resources of this OSBRepository.  # noqa: E501
        :type resources: List[WorkspaceResource]
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'repository_type': RepositoryType,
            'repository_content_types': str,
            'auto_sync': bool,
            'uri': str,
            'user_id': str,
            'default_context': str,
            'resources': List[WorkspaceResource]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'repository_type': 'repository_type',
            'repository_content_types': 'repository_content_types',
            'auto_sync': 'auto_sync',
            'uri': 'uri',
            'user_id': 'user_id',
            'default_context': 'default_context',
            'resources': 'resources'
        }

        self._id = id
        self._name = name
        self._repository_type = repository_type
        self._repository_content_types = repository_content_types
        self._auto_sync = auto_sync
        self._uri = uri
        self._user_id = user_id
        self._default_context = default_context
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'OSBRepository':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OSBRepository of this OSBRepository.  # noqa: E501
        :rtype: OSBRepository
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this OSBRepository.


        :return: The id of this OSBRepository.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OSBRepository.


        :param id: The id of this OSBRepository.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OSBRepository.

        Repository name.  # noqa: E501

        :return: The name of this OSBRepository.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OSBRepository.

        Repository name.  # noqa: E501

        :param name: The name of this OSBRepository.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def repository_type(self):
        """Gets the repository_type of this OSBRepository.


        :return: The repository_type of this OSBRepository.
        :rtype: RepositoryType
        """
        return self._repository_type

    @repository_type.setter
    def repository_type(self, repository_type):
        """Sets the repository_type of this OSBRepository.


        :param repository_type: The repository_type of this OSBRepository.
        :type repository_type: RepositoryType
        """
        if repository_type is None:
            raise ValueError("Invalid value for `repository_type`, must not be `None`")  # noqa: E501

        self._repository_type = repository_type

    @property
    def repository_content_types(self):
        """Gets the repository_content_types of this OSBRepository.

        Comma separated set of Repository Content Types  # noqa: E501

        :return: The repository_content_types of this OSBRepository.
        :rtype: str
        """
        return self._repository_content_types

    @repository_content_types.setter
    def repository_content_types(self, repository_content_types):
        """Sets the repository_content_types of this OSBRepository.

        Comma separated set of Repository Content Types  # noqa: E501

        :param repository_content_types: The repository_content_types of this OSBRepository.
        :type repository_content_types: str
        """
        if repository_content_types is None:
            raise ValueError("Invalid value for `repository_content_types`, must not be `None`")  # noqa: E501

        self._repository_content_types = repository_content_types

    @property
    def auto_sync(self):
        """Gets the auto_sync of this OSBRepository.

        Auto sync of the resources  # noqa: E501

        :return: The auto_sync of this OSBRepository.
        :rtype: bool
        """
        return self._auto_sync

    @auto_sync.setter
    def auto_sync(self, auto_sync):
        """Sets the auto_sync of this OSBRepository.

        Auto sync of the resources  # noqa: E501

        :param auto_sync: The auto_sync of this OSBRepository.
        :type auto_sync: bool
        """
        if auto_sync is None:
            raise ValueError("Invalid value for `auto_sync`, must not be `None`")  # noqa: E501

        self._auto_sync = auto_sync

    @property
    def uri(self):
        """Gets the uri of this OSBRepository.

        URI of the repository  # noqa: E501

        :return: The uri of this OSBRepository.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this OSBRepository.

        URI of the repository  # noqa: E501

        :param uri: The uri of this OSBRepository.
        :type uri: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    @property
    def user_id(self):
        """Gets the user_id of this OSBRepository.

        Repository keycloak user id, will be automatically be set to the logged in user  # noqa: E501

        :return: The user_id of this OSBRepository.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this OSBRepository.

        Repository keycloak user id, will be automatically be set to the logged in user  # noqa: E501

        :param user_id: The user_id of this OSBRepository.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def default_context(self):
        """Gets the default_context of this OSBRepository.

        The default branch to show for this repository  # noqa: E501

        :return: The default_context of this OSBRepository.
        :rtype: str
        """
        return self._default_context

    @default_context.setter
    def default_context(self, default_context):
        """Sets the default_context of this OSBRepository.

        The default branch to show for this repository  # noqa: E501

        :param default_context: The default_context of this OSBRepository.
        :type default_context: str
        """

        self._default_context = default_context

    @property
    def resources(self):
        """Gets the resources of this OSBRepository.

        Resources linked to the Repository  # noqa: E501

        :return: The resources of this OSBRepository.
        :rtype: List[WorkspaceResource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this OSBRepository.

        Resources linked to the Repository  # noqa: E501

        :param resources: The resources of this OSBRepository.
        :type resources: List[WorkspaceResource]
        """

        self._resources = resources
