# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces import util


class Tag(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, tag=None):  # noqa: E501
        """Tag - a model defined in OpenAPI

        :param id: The id of this Tag.  # noqa: E501
        :type id: int
        :param tag: The tag of this Tag.  # noqa: E501
        :type tag: str
        """
        self.openapi_types = {
            'id': int,
            'tag': str
        }

        self.attribute_map = {
            'id': 'id',
            'tag': 'tag'
        }

        self._id = id
        self._tag = tag

    @classmethod
    def from_dict(cls, dikt) -> 'Tag':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tag of this Tag.  # noqa: E501
        :rtype: Tag
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Tag.


        :return: The id of this Tag.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Tag.


        :param id: The id of this Tag.
        :type id: int
        """

        self._id = id

    @property
    def tag(self):
        """Gets the tag of this Tag.


        :return: The tag of this Tag.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Tag.


        :param tag: The tag of this Tag.
        :type tag: str
        """

        self._tag = tag
