# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces import util


class UploadedPart(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, part_number=None, size=None, etag=None):  # noqa: E501
        """UploadedPart - a model defined in OpenAPI

        :param part_number: The part_number of this UploadedPart.  # noqa: E501
        :type part_number: int
        :param size: The size of this UploadedPart.  # noqa: E501
        :type size: int
        :param etag: The etag of this UploadedPart.  # noqa: E501
        :type etag: str
        """
        self.openapi_types = {
            'part_number': int,
            'size': int,
            'etag': str
        }

        self.attribute_map = {
            'part_number': 'part_number',
            'size': 'size',
            'etag': 'etag'
        }

        self._part_number = part_number
        self._size = size
        self._etag = etag

    @classmethod
    def from_dict(cls, dikt) -> 'UploadedPart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UploadedPart of this UploadedPart.  # noqa: E501
        :rtype: UploadedPart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def part_number(self):
        """Gets the part_number of this UploadedPart.


        :return: The part_number of this UploadedPart.
        :rtype: int
        """
        return self._part_number

    @part_number.setter
    def part_number(self, part_number):
        """Sets the part_number of this UploadedPart.


        :param part_number: The part_number of this UploadedPart.
        :type part_number: int
        """

        self._part_number = part_number

    @property
    def size(self):
        """Gets the size of this UploadedPart.


        :return: The size of this UploadedPart.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this UploadedPart.


        :param size: The size of this UploadedPart.
        :type size: int
        """

        self._size = size

    @property
    def etag(self):
        """Gets the etag of this UploadedPart.

        The ETag S3 returned for this part's PUT.  # noqa: E501

        :return: The etag of this UploadedPart.
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this UploadedPart.

        The ETag S3 returned for this part's PUT.  # noqa: E501

        :param etag: The etag of this UploadedPart.
        :type etag: str
        """

        self._etag = etag
