# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.workspace_run_input import WorkspaceRunInput
from workspaces.models.workspace_run_output import WorkspaceRunOutput
from workspaces.models.workspace_run_repo import WorkspaceRunRepo
from workspaces.models.workspace_run_results import WorkspaceRunResults
from workspaces.models.workspace_run_setup import WorkspaceRunSetup
from workspaces import util

from workspaces.models.workspace_run_input import WorkspaceRunInput  # noqa: E501
from workspaces.models.workspace_run_output import WorkspaceRunOutput  # noqa: E501
from workspaces.models.workspace_run_repo import WorkspaceRunRepo  # noqa: E501
from workspaces.models.workspace_run_results import WorkspaceRunResults  # noqa: E501
from workspaces.models.workspace_run_setup import WorkspaceRunSetup  # noqa: E501

class WorkspaceRunRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, repo=None, setup=None, notebooks=None, inputs=None, outputs=None, results=None):  # noqa: E501
        """WorkspaceRunRequest - a model defined in OpenAPI

        :param repo: The repo of this WorkspaceRunRequest.  # noqa: E501
        :type repo: WorkspaceRunRepo
        :param setup: The setup of this WorkspaceRunRequest.  # noqa: E501
        :type setup: WorkspaceRunSetup
        :param notebooks: The notebooks of this WorkspaceRunRequest.  # noqa: E501
        :type notebooks: List[str]
        :param inputs: The inputs of this WorkspaceRunRequest.  # noqa: E501
        :type inputs: List[WorkspaceRunInput]
        :param outputs: The outputs of this WorkspaceRunRequest.  # noqa: E501
        :type outputs: List[WorkspaceRunOutput]
        :param results: The results of this WorkspaceRunRequest.  # noqa: E501
        :type results: WorkspaceRunResults
        """
        self.openapi_types = {
            'repo': WorkspaceRunRepo,
            'setup': WorkspaceRunSetup,
            'notebooks': List[str],
            'inputs': List[WorkspaceRunInput],
            'outputs': List[WorkspaceRunOutput],
            'results': WorkspaceRunResults
        }

        self.attribute_map = {
            'repo': 'repo',
            'setup': 'setup',
            'notebooks': 'notebooks',
            'inputs': 'inputs',
            'outputs': 'outputs',
            'results': 'results'
        }

        self._repo = repo
        self._setup = setup
        self._notebooks = notebooks
        self._inputs = inputs
        self._outputs = outputs
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspaceRunRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkspaceRunRequest of this WorkspaceRunRequest.  # noqa: E501
        :rtype: WorkspaceRunRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def repo(self):
        """Gets the repo of this WorkspaceRunRequest.


        :return: The repo of this WorkspaceRunRequest.
        :rtype: WorkspaceRunRepo
        """
        return self._repo

    @repo.setter
    def repo(self, repo):
        """Sets the repo of this WorkspaceRunRequest.


        :param repo: The repo of this WorkspaceRunRequest.
        :type repo: WorkspaceRunRepo
        """
        if repo is None:
            raise ValueError("Invalid value for `repo`, must not be `None`")  # noqa: E501

        self._repo = repo

    @property
    def setup(self):
        """Gets the setup of this WorkspaceRunRequest.


        :return: The setup of this WorkspaceRunRequest.
        :rtype: WorkspaceRunSetup
        """
        return self._setup

    @setup.setter
    def setup(self, setup):
        """Sets the setup of this WorkspaceRunRequest.


        :param setup: The setup of this WorkspaceRunRequest.
        :type setup: WorkspaceRunSetup
        """

        self._setup = setup

    @property
    def notebooks(self):
        """Gets the notebooks of this WorkspaceRunRequest.

        The notebooks to run, relative to repo.dir, in this order. Each runs in its own folder; the run stops at the first that fails.  # noqa: E501

        :return: The notebooks of this WorkspaceRunRequest.
        :rtype: List[str]
        """
        return self._notebooks

    @notebooks.setter
    def notebooks(self, notebooks):
        """Sets the notebooks of this WorkspaceRunRequest.

        The notebooks to run, relative to repo.dir, in this order. Each runs in its own folder; the run stops at the first that fails.  # noqa: E501

        :param notebooks: The notebooks of this WorkspaceRunRequest.
        :type notebooks: List[str]
        """
        if notebooks is None:
            raise ValueError("Invalid value for `notebooks`, must not be `None`")  # noqa: E501

        self._notebooks = notebooks

    @property
    def inputs(self):
        """Gets the inputs of this WorkspaceRunRequest.

        Copied into the repository before the run.  # noqa: E501

        :return: The inputs of this WorkspaceRunRequest.
        :rtype: List[WorkspaceRunInput]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this WorkspaceRunRequest.

        Copied into the repository before the run.  # noqa: E501

        :param inputs: The inputs of this WorkspaceRunRequest.
        :type inputs: List[WorkspaceRunInput]
        """

        self._inputs = inputs

    @property
    def outputs(self):
        """Gets the outputs of this WorkspaceRunRequest.

        Copied out of the repository after the run, also when it fails.  # noqa: E501

        :return: The outputs of this WorkspaceRunRequest.
        :rtype: List[WorkspaceRunOutput]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this WorkspaceRunRequest.

        Copied out of the repository after the run, also when it fails.  # noqa: E501

        :param outputs: The outputs of this WorkspaceRunRequest.
        :type outputs: List[WorkspaceRunOutput]
        """

        self._outputs = outputs

    @property
    def results(self):
        """Gets the results of this WorkspaceRunRequest.


        :return: The results of this WorkspaceRunRequest.
        :rtype: WorkspaceRunResults
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this WorkspaceRunRequest.


        :param results: The results of this WorkspaceRunRequest.
        :type results: WorkspaceRunResults
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results
