# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.pagination import Pagination
from workspaces.models.workspace import Workspace
from workspaces import util

from workspaces.models.pagination import Pagination  # noqa: E501
from workspaces.models.workspace import Workspace  # noqa: E501

class WorkspaceGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pagination=None, workspaces=None):  # noqa: E501
        """WorkspaceGet200Response - a model defined in OpenAPI

        :param pagination: The pagination of this WorkspaceGet200Response.  # noqa: E501
        :type pagination: Pagination
        :param workspaces: The workspaces of this WorkspaceGet200Response.  # noqa: E501
        :type workspaces: List[Workspace]
        """
        self.openapi_types = {
            'pagination': Pagination,
            'workspaces': List[Workspace]
        }

        self.attribute_map = {
            'pagination': 'pagination',
            'workspaces': 'workspaces'
        }

        self._pagination = pagination
        self._workspaces = workspaces

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspaceGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _workspace_get_200_response of this WorkspaceGet200Response.  # noqa: E501
        :rtype: WorkspaceGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pagination(self):
        """Gets the pagination of this WorkspaceGet200Response.


        :return: The pagination of this WorkspaceGet200Response.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this WorkspaceGet200Response.


        :param pagination: The pagination of this WorkspaceGet200Response.
        :type pagination: Pagination
        """

        self._pagination = pagination

    @property
    def workspaces(self):
        """Gets the workspaces of this WorkspaceGet200Response.


        :return: The workspaces of this WorkspaceGet200Response.
        :rtype: List[Workspace]
        """
        return self._workspaces

    @workspaces.setter
    def workspaces(self, workspaces):
        """Sets the workspaces of this WorkspaceGet200Response.


        :param workspaces: The workspaces of this WorkspaceGet200Response.
        :type workspaces: List[Workspace]
        """

        self._workspaces = workspaces
