# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces.models.resource_origin import ResourceOrigin
from workspaces import util

from workspaces.models.resource_origin import ResourceOrigin  # noqa: E501

class WorkspacesControllersWorkspaceControllerImportResourcesRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, resourceorigins=None):  # noqa: E501
        """WorkspacesControllersWorkspaceControllerImportResourcesRequest - a model defined in OpenAPI

        :param resourceorigins: The resourceorigins of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.  # noqa: E501
        :type resourceorigins: List[ResourceOrigin]
        """
        self.openapi_types = {
            'resourceorigins': List[ResourceOrigin]
        }

        self.attribute_map = {
            'resourceorigins': 'resourceorigins'
        }

        self._resourceorigins = resourceorigins

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspacesControllersWorkspaceControllerImportResourcesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The workspaces_controllers_workspace_controller_import_resources_request of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.  # noqa: E501
        :rtype: WorkspacesControllersWorkspaceControllerImportResourcesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resourceorigins(self):
        """Gets the resourceorigins of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.


        :return: The resourceorigins of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.
        :rtype: List[ResourceOrigin]
        """
        return self._resourceorigins

    @resourceorigins.setter
    def resourceorigins(self, resourceorigins):
        """Sets the resourceorigins of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.


        :param resourceorigins: The resourceorigins of this WorkspacesControllersWorkspaceControllerImportResourcesRequest.
        :type resourceorigins: List[ResourceOrigin]
        """

        self._resourceorigins = resourceorigins
