# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workspaces.models.base_model_ import Model
from workspaces import util

class WorkspaceRunRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notebooks_dir=None, input_path=None, input_dir=None, output_dir=None):  # noqa: E501
        """WorkspaceRunRequest - a model defined in OpenAPI

        :param notebooks_dir: The notebooks_dir of this WorkspaceRunRequest.  # noqa: E501
        :type notebooks_dir: str
        :param input_path: The input_path of this WorkspaceRunRequest.  # noqa: E501
        :type input_path: str
        :param input_dir: The input_dir of this WorkspaceRunRequest.  # noqa: E501
        :type input_dir: str
        :param output_dir: The output_dir of this WorkspaceRunRequest.  # noqa: E501
        :type output_dir: str
        """
        self.openapi_types = {
            'notebooks_dir': str,
            'input_path': str,
            'input_dir': str,
            'output_dir': str
        }

        self.attribute_map = {
            'notebooks_dir': 'notebooks_dir',
            'input_path': 'input_path',
            'input_dir': 'input_dir',
            'output_dir': 'output_dir'
        }

        self._notebooks_dir = notebooks_dir
        self._input_path = input_path
        self._input_dir = input_dir
        self._output_dir = output_dir

    @classmethod
    def from_dict(cls, dikt) -> 'WorkspaceRunRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkspaceRunRequest of this WorkspaceRunRequest.  # noqa: E501
        :rtype: WorkspaceRunRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notebooks_dir(self):
        """Gets the notebooks_dir of this WorkspaceRunRequest.

        The repository's notebooks folder on the volume, e.g. four-choice-example-main/notebooks. Its parent is the repository.  # noqa: E501

        :return: The notebooks_dir of this WorkspaceRunRequest.
        :rtype: str
        """
        return self._notebooks_dir

    @notebooks_dir.setter
    def notebooks_dir(self, notebooks_dir):
        """Sets the notebooks_dir of this WorkspaceRunRequest.

        The repository's notebooks folder on the volume, e.g. four-choice-example-main/notebooks. Its parent is the repository.  # noqa: E501

        :param notebooks_dir: The notebooks_dir of this WorkspaceRunRequest.
        :type notebooks_dir: str
        """
        if notebooks_dir is None:
            raise ValueError("Invalid value for `notebooks_dir`, must not be `None`")  # noqa: E501

        self._notebooks_dir = notebooks_dir

    @property
    def input_path(self):
        """Gets the input_path of this WorkspaceRunRequest.

        The imported data on the volume (a file, or a folder), if any.  # noqa: E501

        :return: The input_path of this WorkspaceRunRequest.
        :rtype: str
        """
        return self._input_path

    @input_path.setter
    def input_path(self, input_path):
        """Sets the input_path of this WorkspaceRunRequest.

        The imported data on the volume (a file, or a folder), if any.  # noqa: E501

        :param input_path: The input_path of this WorkspaceRunRequest.
        :type input_path: str
        """

        self._input_path = input_path

    @property
    def input_dir(self):
        """Gets the input_dir of this WorkspaceRunRequest.

        Repository-relative folder the notebooks read their input from (e.g. example_data); for the run it holds input_path instead.  # noqa: E501

        :return: The input_dir of this WorkspaceRunRequest.
        :rtype: str
        """
        return self._input_dir

    @input_dir.setter
    def input_dir(self, input_dir):
        """Sets the input_dir of this WorkspaceRunRequest.

        Repository-relative folder the notebooks read their input from (e.g. example_data); for the run it holds input_path instead.  # noqa: E501

        :param input_dir: The input_dir of this WorkspaceRunRequest.
        :type input_dir: str
        """

        self._input_dir = input_dir

    @property
    def output_dir(self):
        """Gets the output_dir of this WorkspaceRunRequest.

        Where results go, relative to the volume; the run adds its own folder. Default results.  # noqa: E501

        :return: The output_dir of this WorkspaceRunRequest.
        :rtype: str
        """
        return self._output_dir

    @output_dir.setter
    def output_dir(self, output_dir):
        """Sets the output_dir of this WorkspaceRunRequest.

        Where results go, relative to the volume; the run adds its own folder. Default results.  # noqa: E501

        :param output_dir: The output_dir of this WorkspaceRunRequest.
        :type output_dir: str
        """

        self._output_dir = output_dir
