/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface EmberValidateUploadResponse
 */
export interface EmberValidateUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof EmberValidateUploadResponse
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof EmberValidateUploadResponse
     */
    assetPath: string;
    /**
     * 
     * @type {string}
     * @memberof EmberValidateUploadResponse
     */
    dandisetId?: string;
    /**
     * 
     * @type {string}
     * @memberof EmberValidateUploadResponse
     */
    dandisetUrl?: string;
    /**
     * Where the asset's bytes can be fetched from, e.g. by OSB's workspace import.
     * @type {string}
     * @memberof EmberValidateUploadResponse
     */
    downloadUrl: string;
}

export function EmberValidateUploadResponseFromJSON(json: any): EmberValidateUploadResponse {
    return EmberValidateUploadResponseFromJSONTyped(json, false);
}

export function EmberValidateUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmberValidateUploadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetId': json['asset_id'],
        'assetPath': json['asset_path'],
        'dandisetId': !exists(json, 'dandiset_id') ? undefined : json['dandiset_id'],
        'dandisetUrl': !exists(json, 'dandiset_url') ? undefined : json['dandiset_url'],
        'downloadUrl': json['download_url'],
    };
}

export function EmberValidateUploadResponseToJSON(value?: EmberValidateUploadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset_id': value.assetId,
        'asset_path': value.assetPath,
        'dandiset_id': value.dandisetId,
        'dandiset_url': value.dandisetUrl,
        'download_url': value.downloadUrl,
    };
}

