/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmberUploadedPart,
    EmberUploadedPartFromJSON,
    EmberUploadedPartFromJSONTyped,
    EmberUploadedPartToJSON,
} from './EmberUploadedPart';

/**
 * 
 * @export
 * @interface EmberValidateUploadRequest
 */
export interface EmberValidateUploadRequest {
    /**
     * Keycloak username whose EMBER-DANDI key (user attribute EMBER_API_KEY) signs the upload.
     * @type {string}
     * @memberof EmberValidateUploadRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof EmberValidateUploadRequest
     */
    dandisetId: string;
    /**
     * Omitted when get_upload_urls returned a blob_id (nothing was uploaded).
     * @type {string}
     * @memberof EmberValidateUploadRequest
     */
    uploadId?: string;
    /**
     * The path get_upload_urls returned.
     * @type {string}
     * @memberof EmberValidateUploadRequest
     */
    path: string;
    /**
     * Omitted when get_upload_urls returned a blob_id.
     * @type {Array<EmberUploadedPart>}
     * @memberof EmberValidateUploadRequest
     */
    parts?: Array<EmberUploadedPart>;
    /**
     * Echoed from get_upload_urls; when present, complete/validate are skipped.
     * @type {string}
     * @memberof EmberValidateUploadRequest
     */
    blobId?: string;
}

export function EmberValidateUploadRequestFromJSON(json: any): EmberValidateUploadRequest {
    return EmberValidateUploadRequestFromJSONTyped(json, false);
}

export function EmberValidateUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmberValidateUploadRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'dandisetId': json['dandiset_id'],
        'uploadId': !exists(json, 'upload_id') ? undefined : json['upload_id'],
        'path': json['path'],
        'parts': !exists(json, 'parts') ? undefined : ((json['parts'] as Array<any>).map(EmberUploadedPartFromJSON)),
        'blobId': !exists(json, 'blob_id') ? undefined : json['blob_id'],
    };
}

export function EmberValidateUploadRequestToJSON(value?: EmberValidateUploadRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'dandiset_id': value.dandisetId,
        'upload_id': value.uploadId,
        'path': value.path,
        'parts': value.parts === undefined ? undefined : ((value.parts as Array<any>).map(EmberUploadedPartToJSON)),
        'blob_id': value.blobId,
    };
}

