/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmberUploadPart,
    EmberUploadPartFromJSON,
    EmberUploadPartFromJSONTyped,
    EmberUploadPartToJSON,
} from './EmberUploadPart';

/**
 * 
 * @export
 * @interface EmberUploadUrlsResponse
 */
export interface EmberUploadUrlsResponse {
    /**
     * 
     * @type {string}
     * @memberof EmberUploadUrlsResponse
     */
    dandisetId: string;
    /**
     * Absent when the content was already in EMBER-DANDI.
     * @type {string}
     * @memberof EmberUploadUrlsResponse
     */
    uploadId?: string;
    /**
     * Asset path, derived server-side from the caller's identity.
     * @type {string}
     * @memberof EmberUploadUrlsResponse
     */
    path: string;
    /**
     * 
     * @type {Array<EmberUploadPart>}
     * @memberof EmberUploadUrlsResponse
     */
    parts: Array<EmberUploadPart>;
    /**
     * Set only when the content was already in EMBER-DANDI (parts is then empty).
     * @type {string}
     * @memberof EmberUploadUrlsResponse
     */
    blobId?: string;
}

export function EmberUploadUrlsResponseFromJSON(json: any): EmberUploadUrlsResponse {
    return EmberUploadUrlsResponseFromJSONTyped(json, false);
}

export function EmberUploadUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmberUploadUrlsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dandisetId': json['dandiset_id'],
        'uploadId': !exists(json, 'upload_id') ? undefined : json['upload_id'],
        'path': json['path'],
        'parts': ((json['parts'] as Array<any>).map(EmberUploadPartFromJSON)),
        'blobId': !exists(json, 'blob_id') ? undefined : json['blob_id'],
    };
}

export function EmberUploadUrlsResponseToJSON(value?: EmberUploadUrlsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dandiset_id': value.dandisetId,
        'upload_id': value.uploadId,
        'path': value.path,
        'parts': ((value.parts as Array<any>).map(EmberUploadPartToJSON)),
        'blob_id': value.blobId,
    };
}

