/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GITRepositoryAllOf,
    GITRepositoryAllOfFromJSON,
    GITRepositoryAllOfFromJSONTyped,
    GITRepositoryAllOfToJSON,
    OSBRepositoryContext,
    OSBRepositoryContextFromJSON,
    OSBRepositoryContextFromJSONTyped,
    OSBRepositoryContextToJSON,
    RepositoryBase,
    RepositoryBaseFromJSON,
    RepositoryBaseFromJSONTyped,
    RepositoryBaseToJSON,
    RepositoryType,
    RepositoryTypeFromJSON,
    RepositoryTypeFromJSONTyped,
    RepositoryTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface GITRepository
 */
export interface GITRepository {
    /**
     * 
     * @type {number}
     * @memberof GITRepository
     */
    id?: number;
    /**
     * Repository name.
     * @type {string}
     * @memberof GITRepository
     */
    name: string;
    /**
     * 
     * @type {RepositoryType}
     * @memberof GITRepository
     */
    repositoryType: RepositoryType;
    /**
     * Comma separated set of Repository Content Types
     * @type {string}
     * @memberof GITRepository
     */
    repositoryContentTypes: string;
    /**
     * Auto sync of the resources
     * @type {boolean}
     * @memberof GITRepository
     */
    autoSync: boolean;
    /**
     * URI of the repository
     * @type {string}
     * @memberof GITRepository
     */
    uri: string;
    /**
     * Repository keycloak user id, will be automatically be set to the logged in user
     * @type {string}
     * @memberof GITRepository
     */
    userId?: string;
    /**
     * List of contexts with used/referenced resources in this repository
     * @type {Array<OSBRepositoryContext>}
     * @memberof GITRepository
     */
    usedContexts?: Array<OSBRepositoryContext>;
    /**
     * The default branch to show for this repository
     * @type {string}
     * @memberof GITRepository
     */
    defaultContext: string;
}

export function GITRepositoryFromJSON(json: any): GITRepository {
    return GITRepositoryFromJSONTyped(json, false);
}

export function GITRepositoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITRepository {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'repositoryType': RepositoryTypeFromJSON(json['repository_type']),
        'repositoryContentTypes': json['repository_content_types'],
        'autoSync': json['auto_sync'],
        'uri': json['uri'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'usedContexts': !exists(json, 'used_contexts') ? undefined : ((json['used_contexts'] as Array<any>).map(OSBRepositoryContextFromJSON)),
        'defaultContext': json['default_context'],
    };
}

export function GITRepositoryToJSON(value?: GITRepository | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'repository_type': RepositoryTypeToJSON(value.repositoryType),
        'repository_content_types': value.repositoryContentTypes,
        'auto_sync': value.autoSync,
        'uri': value.uri,
        'user_id': value.userId,
        'used_contexts': value.usedContexts === undefined ? undefined : ((value.usedContexts as Array<any>).map(OSBRepositoryContextToJSON)),
        'default_context': value.defaultContext,
    };
}


