/* tslint:disable */
/* eslint-disable */
/**
 * Workspaces manager API
 * MetaCell Cloudharness Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mnp@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Resource type:  * e - Experimental  * m - Model  * g - Generic 
 * @export
 * @enum {string}
 */
export enum ResourceType {
    E = 'e',
    M = 'm',
    G = 'g'
}

export function ResourceTypeFromJSON(json: any): ResourceType {
    return ResourceTypeFromJSONTyped(json, false);
}

export function ResourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceType {
    return json as ResourceType;
}

export function ResourceTypeToJSON(value?: ResourceType | null): any {
    return value as any;
}

