/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Resource Base
 * @export
 * @interface ResourceBase
 */
export interface ResourceBase {
    /**
     * file name
     * @type {string}
     * @memberof ResourceBase
     */
    name?: string;
    /**
     * Download URL of the Resource
     * @type {string}
     * @memberof ResourceBase
     */
    path?: string;
}

export function ResourceBaseFromJSON(json: any): ResourceBase {
    return ResourceBaseFromJSONTyped(json, false);
}

export function ResourceBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ResourceBaseToJSON(value?: ResourceBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'path': value.path,
    };
}


