/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadInitRequest
 */
export interface UploadInitRequest {
    /**
     * Slug of the selected protocol; becomes the first segment of the asset path.
     * @type {string}
     * @memberof UploadInitRequest
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadInitRequest
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof UploadInitRequest
     */
    size: number;
    /**
     * S3-multipart digest in DANDI's format (32 hex chars, a dash, the part count), computed in the browser since the bytes never reach this server.
     * @type {string}
     * @memberof UploadInitRequest
     */
    dandiEtag: string;
}

export function UploadInitRequestFromJSON(json: any): UploadInitRequest {
    return UploadInitRequestFromJSONTyped(json, false);
}

export function UploadInitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadInitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': !exists(json, 'task_id') ? undefined : json['task_id'],
        'filename': json['filename'],
        'size': json['size'],
        'dandiEtag': json['dandi_etag'],
    };
}

export function UploadInitRequestToJSON(value?: UploadInitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_id': value.taskId,
        'filename': value.filename,
        'size': value.size,
        'dandi_etag': value.dandiEtag,
    };
}


