/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFinalizeResponse
 */
export interface UploadFinalizeResponse {
    /**
     * Path of the registered DANDI asset.
     * @type {string}
     * @memberof UploadFinalizeResponse
     */
    assetPath: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFinalizeResponse
     */
    dandisetUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFinalizeResponse
     */
    workspaceId: number;
    /**
     * Everything the protocol script printed, or an explanation of why it did not run. Absent when no script_url was supplied.
     * @type {string}
     * @memberof UploadFinalizeResponse
     */
    scriptOutput?: string;
}

export function UploadFinalizeResponseFromJSON(json: any): UploadFinalizeResponse {
    return UploadFinalizeResponseFromJSONTyped(json, false);
}

export function UploadFinalizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFinalizeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetPath': json['asset_path'],
        'dandisetUrl': !exists(json, 'dandiset_url') ? undefined : json['dandiset_url'],
        'workspaceId': json['workspace_id'],
        'scriptOutput': !exists(json, 'script_output') ? undefined : json['script_output'],
    };
}

export function UploadFinalizeResponseToJSON(value?: UploadFinalizeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset_path': value.assetPath,
        'dandiset_url': value.dandisetUrl,
        'workspace_id': value.workspaceId,
        'script_output': value.scriptOutput,
    };
}


