/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface WorkspaceRunResponse
 */
export interface WorkspaceRunResponse {
    /**
     * The run's id, for GET /workspace/{id}/run/{workflow}.
     * @type {string}
     * @memberof WorkspaceRunResponse
     */
    workflow: string;
}

export function WorkspaceRunResponseFromJSON(json: any): WorkspaceRunResponse {
    return WorkspaceRunResponseFromJSONTyped(json, false);
}

export function WorkspaceRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceRunResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workflow': json['workflow'],
    };
}

export function WorkspaceRunResponseToJSON(value?: WorkspaceRunResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workflow': value.workflow,
    };
}


