/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A run's workflow, as CloudHarness's workflows API reports an operation.
 * @export
 * @interface WorkspaceRunStatus
 */
export interface WorkspaceRunStatus {
    /**
     * The workflow name, from POST /workspace/{id}/run.
     * @type {string}
     * @memberof WorkspaceRunStatus
     */
    name: string;
    /**
     * Argo's phase of the workflow.
     * @type {string}
     * @memberof WorkspaceRunStatus
     */
    status: WorkspaceRunStatusStatusEnum;
    /**
     * Set when the run failed (e.g. which notebook).
     * @type {string}
     * @memberof WorkspaceRunStatus
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum WorkspaceRunStatusStatusEnum {
    Pending = 'Pending',
    Running = 'Running',
    Succeeded = 'Succeeded',
    Skipped = 'Skipped',
    Failed = 'Failed',
    Error = 'Error'
}

export function WorkspaceRunStatusFromJSON(json: any): WorkspaceRunStatus {
    return WorkspaceRunStatusFromJSONTyped(json, false);
}

export function WorkspaceRunStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceRunStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function WorkspaceRunStatusToJSON(value?: WorkspaceRunStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'status': value.status,
        'message': value.message,
    };
}


