/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface WorkspaceRunResults
 */
export interface WorkspaceRunResults {
    /**
     * Folder for the executed notebooks, created only if every notebook passes; if one fails, they are in <folder>.failed instead.
     * @type {string}
     * @memberof WorkspaceRunResults
     */
    notebooks: string;
    /**
     * The run's log file. The run is refused if it already exists.
     * @type {string}
     * @memberof WorkspaceRunResults
     */
    log: string;
}

export function WorkspaceRunResultsFromJSON(json: any): WorkspaceRunResults {
    return WorkspaceRunResultsFromJSONTyped(json, false);
}

export function WorkspaceRunResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceRunResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notebooks': json['notebooks'],
        'log': json['log'],
    };
}

export function WorkspaceRunResultsToJSON(value?: WorkspaceRunResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notebooks': value.notebooks,
        'log': value.log,
    };
}


