/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceRunRequest
 */
export interface WorkspaceRunRequest {
    /**
     * The repository's notebooks folder on the volume, e.g. four-choice-example-main/notebooks. Its parent is the repository.
     * @type {string}
     * @memberof WorkspaceRunRequest
     */
    notebooksDir: string;
    /**
     * The imported data on the volume (a file, or a folder), if any.
     * @type {string}
     * @memberof WorkspaceRunRequest
     */
    inputPath?: string;
    /**
     * Repository-relative folder the notebooks read their input from (e.g. example_data); for the run it holds input_path instead.
     * @type {string}
     * @memberof WorkspaceRunRequest
     */
    inputDir?: string;
    /**
     * Where results go, relative to the volume; the run adds its own folder. Default results.
     * @type {string}
     * @memberof WorkspaceRunRequest
     */
    outputDir?: string;
}

export function WorkspaceRunRequestFromJSON(json: any): WorkspaceRunRequest {
    return WorkspaceRunRequestFromJSONTyped(json, false);
}

export function WorkspaceRunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceRunRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notebooksDir': json['notebooks_dir'],
        'inputPath': !exists(json, 'input_path') ? undefined : json['input_path'],
        'inputDir': !exists(json, 'input_dir') ? undefined : json['input_dir'],
        'outputDir': !exists(json, 'output_dir') ? undefined : json['output_dir'],
    };
}

export function WorkspaceRunRequestToJSON(value?: WorkspaceRunRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notebooks_dir': value.notebooksDir,
        'input_path': value.inputPath,
        'input_dir': value.inputDir,
        'output_dir': value.outputDir,
    };
}


