version: '1.0'
stages:
- prepare
- build
- deploy
- publish
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  post_main_clone:
    title: Post main clone
    type: parallel
    stage: prepare
    steps:
    - title: Cloning cloud-harness repository...
      type: git-clone
      stage: prepare
      repo: https://github.com/MetaCell/cloud-harness.git
      revision: '${{CLOUDHARNESS_BRANCH}}'
      working_directory: .
      git: github
  prepare_deployment:
    title: Prepare helm chart
    image: python:3.7
    stage: prepare
    working_directory: .
    commands:
    - pip install cloud-harness/utilities
    - harness-deployment cloud-harness . -m build -t ${{CF_BUILD_ID}} -d ${{DOMAIN}}
      -r ${{REGISTRY}} -rs ${{REGISTRY_SECRET}} -e dev
  prepare_deployment_view:
    commands:
    - helm template ./deployment/helm --debug -n ${{NAME}}
    environment:
    - ACTION=auth
    - KUBE_CONTEXT=${{NAME}}
    image: codefresh/cfstep-helm:3.4.1
    stage: prepare
    title: View helm chart
  build_base_images:
    title: Build base images
    type: parallel
    stage: build
    steps:
      cloudharness-base:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: infrastructure/base-images/cloudharness-base/Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: cloudharness-base
        title: Cloudharness base
        working_directory: ./build
      cloudharness-base-debian:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: infrastructure/base-images/cloudharness-base-debian/Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: cloudharness-base-debian
        title: Cloudharness base debian
        working_directory: ./build
      cloudharness-frontend-build:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: infrastructure/base-images/cloudharness-frontend-build/Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: cloudharness-frontend-build
        title: Cloudharness frontend build
        working_directory: ./build
  build_static_images:
    title: Build static images
    type: parallel
    stage: build
    steps:
      cloudharness-flask:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: cloudharness-flask
        title: Cloudharness flask
        working_directory: ./build/infrastructure/common-images/cloudharness-flask
  build_application_images:
    type: parallel
    stage: build
    steps:
      volumemanager:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: volumemanager
        title: Volumemanager
        working_directory: ./build/applications/volumemanager/server
      accounts:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: accounts
        title: Accounts
        working_directory: ./build/applications/accounts
      osb-portal:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: osb-portal
        title: Osb portal
        working_directory: ./build/applications/osb-portal
      common:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: common
        title: Common
        working_directory: ./build/applications/common/server
      workspaces:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workspaces
        title: Workspaces
        working_directory: ./build/applications/workspaces/server
      workflows-print-file:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows-print-file
        title: Workflows print file
        working_directory: ./build/applications/workflows/tasks/print-file
      workflows-extract-download:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows-extract-download
        title: Workflows extract download
        working_directory: ./build/applications/workflows/tasks/extract-download
      workflows-send-result-event:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows-send-result-event
        title: Workflows send result event
        working_directory: ./build/applications/workflows/tasks/send-result-event
      workflows-notify-queue:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows-notify-queue
        title: Workflows notify queue
        working_directory: ./build/applications/workflows/tasks/notify-queue
      workflows-extract-s3:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows-extract-s3
        title: Workflows extract s3
        working_directory: ./build/applications/workflows/tasks/extract-s3
      workflows:
        type: build
        stage: build
        tag: '${{CF_BUILD_ID}}'
        dockerfile: Dockerfile
        build_arguments:
        - REGISTRY=${{REGISTRY}}
        - TAG=${{CF_BUILD_ID}}
        - NAMESPACE=${{NAMESPACE}}
        - DOMAIN=${{DOMAIN}}
        registry: '${{CODEFRESH_REGISTRY}}'
        no_cf_cache: false
        image_name: workflows
        title: Workflows
        working_directory: ./build/applications/workflows/server
  deployment:
    stage: deploy
    image: codefresh/cfstep-helm:3.4.1
    title: Installing chart
    environment:
    - CHART_REF=./deployment/helm
    - RELEASE_NAME=${{NAMESPACE}}
    - KUBE_CONTEXT=${{CLUSTER_NAME}}
    - NAMESPACE=${{NAMESPACE}}
    - CHART_VERSION=${{DEPLOYMENT_PUBLISH_TAG}}
    - HELM_REPO_USE_HTTP=false
    - HELM_REPO_CONTEXT_PATH=
    - TIMEOUT=600s
    - VALUESFILE_values=./deployment/helm/values.yaml
  publish:
    type: parallel
    stage: publish
    steps:
      publish_cloudharness-base:
        stage: publish
        type: push
        title: Cloudharness base
        candidate: '${{REGISTRY}}/cloudharness-base:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-base-debian:
        stage: publish
        type: push
        title: Cloudharness base debian
        candidate: '${{REGISTRY}}/cloudharness-base-debian:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-frontend-build:
        stage: publish
        type: push
        title: Cloudharness frontend build
        candidate: '${{REGISTRY}}/cloudharness-frontend-build:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-flask:
        stage: publish
        type: push
        title: Cloudharness flask
        candidate: '${{REGISTRY}}/cloudharness-flask:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_volumemanager:
        stage: publish
        type: push
        title: Volumemanager
        candidate: '${{REGISTRY}}/volumemanager:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_accounts:
        stage: publish
        type: push
        title: Accounts
        candidate: '${{REGISTRY}}/accounts:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_osb-portal:
        stage: publish
        type: push
        title: Osb portal
        candidate: '${{REGISTRY}}/osb-portal:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_common:
        stage: publish
        type: push
        title: Common
        candidate: '${{REGISTRY}}/common:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workspaces:
        stage: publish
        type: push
        title: Workspaces
        candidate: '${{REGISTRY}}/workspaces:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-print-file:
        stage: publish
        type: push
        title: Workflows print file
        candidate: '${{REGISTRY}}/workflows-print-file:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-extract-download:
        stage: publish
        type: push
        title: Workflows extract download
        candidate: '${{REGISTRY}}/workflows-extract-download:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-send-result-event:
        stage: publish
        type: push
        title: Workflows send result event
        candidate: '${{REGISTRY}}/workflows-send-result-event:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-notify-queue:
        stage: publish
        type: push
        title: Workflows notify queue
        candidate: '${{REGISTRY}}/workflows-notify-queue:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-extract-s3:
        stage: publish
        type: push
        title: Workflows extract s3
        candidate: '${{REGISTRY}}/workflows-extract-s3:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows:
        stage: publish
        type: push
        title: Workflows
        candidate: '${{REGISTRY}}/workflows:${{CF_BUILD_ID}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        registry: '${{REGISTRY_PUBLISH_URL}}'
