kind: ConfigMap
apiVersion: v1
metadata:
  name: "jupyterhub-notebook-config"
  labels:
    app: jupyterhub
data:
  {{- (.Files.Glob "resources/jupyterhub/applications/*").AsConfig | nindent 2 }}
---
