/* tslint:disable */
/* eslint-disable */
/**
 * OSB Workspaces manager API
 * Opensource Brain Platform - Reference Workspaces manager API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    WorkspaceRunRequest,
    WorkspaceRunRequestFromJSON,
    WorkspaceRunRequestToJSON,
    WorkspaceRunResponse,
    WorkspaceRunResponseFromJSON,
    WorkspaceRunResponseToJSON,
} from '../models';

export interface RunNotebooksRequest {
    id: number;
    workspaceRunRequest: WorkspaceRunRequest;
}

/**
 * 
 */
export class RunApi extends runtime.BaseAPI {

    /**
     * Run notebooks of a repository on the workspace\'s volume (papermill in an Argo task), in the order given, after setting up what the request names (requirements, PYTHONPATH, installs). Returns at once.
     */
    async runNotebooksRaw(requestParameters: RunNotebooksRequest): Promise<runtime.ApiResponse<WorkspaceRunResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling runNotebooks.');
        }

        if (requestParameters.workspaceRunRequest === null || requestParameters.workspaceRunRequest === undefined) {
            throw new runtime.RequiredError('workspaceRunRequest','Required parameter requestParameters.workspaceRunRequest was null or undefined when calling runNotebooks.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/workspace/{id}/run`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceRunRequestToJSON(requestParameters.workspaceRunRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceRunResponseFromJSON(jsonValue));
    }

    /**
     * Run notebooks of a repository on the workspace\'s volume (papermill in an Argo task), in the order given, after setting up what the request names (requirements, PYTHONPATH, installs). Returns at once.
     */
    async runNotebooks(requestParameters: RunNotebooksRequest): Promise<WorkspaceRunResponse> {
        const response = await this.runNotebooksRaw(requestParameters);
        return await response.value();
    }

}
