harness:
  sentry: false
  # dependencies:
  #   soft:
  #     - accounts
  #     - accounts-api
  #     - workspaces
  #     - workflows
  #     - jupyterhub
  #     - jupyterlab
  #     - backoffice