harness:
  subdomain: notebooks
  service:
    auto: false
    port: 80
    name: proxy-public
  deployment:
    auto: false
  dependencies:
    build:
      - cloudharness-base
    hard:
      - jupyterhub
  jupyterhub:
    args: ["--debug", "--NotebookApp.default_url=/lab", "--NotebookApp.notebook_dir=/opt/workspace"]
    applicationHook: "osb_jupyter.change_pod_manifest"
    extraConfig:
      timing: |
        c.Spawner.port = 8000
        c.Spawner.http_timeout = 300
        c.Spawner.start_timeout = 300

        c.JupyterHub.tornado_settings = { "headers": { "Content-Security-Policy": "frame-ancestors 'self' localhost:3000 *.osb.local osb.local localhost *.metacell.us *.opensourcebrain.org "}}

singleuser:
  cpu:
    limit: 0.1
    guarantee: 0.02
  memory:
    limit: 0.5G
    guarantee: 0.1G