name: Docker Image Build NetPyNE-UI

on:
  push:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]
  pull_request:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone Netpyne UI dependencies
      run: |
        mkdir -p applications/netpyne/dependencies
        export BRANCH_TAG=$(grep "branch_tag:" applications/nwb-explorer/deploy/values.yaml | awk '{print $2}')
        echo "Using branch: $BRANCH_TAG"
        git clone --branch $BRANCH_TAG https://github.com/MetaCell/NetPyNE-UI.git applications/netpyne/dependencies/NetPyNE-UI

    - name: Build the Docker image
      run: |
        cd applications/netpyne
        docker build -t mynpui -f Dockerfile --no-cache .
        
    - name: Info on Docker image sizes
      run: |
        docker images

    - name: Run the Docker container and list python installs
      run: |
        docker run -t --rm --entrypoint /bin/bash mynpui  -c "pip3 list"
