name: Docker Image Build JupyterLab

on:
  push:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]
  pull_request:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        cd applications/jupyterlab
        ./build_local.sh 

    - name: Info on Docker image sizes
      run: |
        docker images

    - name: Run the Docker container and list python installs
      run: |
        cd applications/jupyterlab
        ./pip_omv_info.sh
