name: Test local install using minikube

on:
  push:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]
  pull_request:
    branches: [ master, dev*, feature/docker*, feature/repo*, jupyterhub-update ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]
        runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install CloudHarness
      run: |
        ./local-scripts/osbv2-local.sh -u

    - name: Run version info 
      run: |
        ./local-scripts/osbv2-local.sh -v

    - name: Test local deploy
      run: |
        ./local-scripts/osbv2-local.sh -d
    
    - name: Info on Docker image sizes
      run: |
        docker images

        
